const _ = require("lodash");  //bring in the lodash

let jsRandom = Math.floor((Math.random() * 100) + 1); //js

let _Random = _.random(1, 100);//using lodash


let combinedArray = [1, 2, 3] + [4, 5, 6]; //js

let combined_Array = _.concat([1, 2, 3], [4, 5, 6]); //using lodash

console.log("Number generated by JS: " + jsRandom)
console.log("Number genereated by Lodash: " + _Random);

console.log(combinedArray);
console.log(combined_Array);